on:
  release:
    types: [created]

name: Add artifacts to release

jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.0
        with:
          version: 0.11.0

      - name: Checkout project
        uses: actions/checkout@v3

      - name: zig build test
        run: |
          zig env
          zig build test

      - name: zig build cross -Doptimize=ReleaseSmall
        run: |
          zig env
          zig build cross -Doptimize=ReleaseSmall

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zig-out/cross/*/findup-*.tgz'
